export enum GameEvent {
    ReqLogin = 'ReqLogin',
    ReqKeepAlive = 'ReqKeepAlive',
    ReqEnterRoom = 'ReqEnterRoom',
    ReqLeaveRoom = 'ReqLeaveRoom',
    ReqRoomReady = 'ReqRoomReady',
    ReqCallScore = 'ReqCallScore',
    ReqWatchCards = 'ReqWatchCards',
    ReqPlayCards = 'ReqPlayCards',
    ReqEnterRoomUpdate = 'ReqEnterRoomUpdate',
    ReqLeaveRoomUpdate = 'ReqLeaveRoomUpdate',
    ReqRoomReadyUpdate = 'ReqRoomReadyUpdate',
    ReqCallScoreUpdate = 'ReqCallScoreUpdate',
    ReqPlayCardsUpdate = 'ReqPlayCardsUpdate',
}